import mongoose from "mongoose";
import Address from "../models/AddressShema.js";
import User from "../models/UserSchema.js";
import Product from "../models/ProductSchema.js";
import Review from "../models/ReviewSchema.js";
import Admin from "../models/AdminSchema.js";

const dbUrl =
  "mongodb+srv://ujjwalAndNitinDb:Tn99S9ZWR6oZjJOE@madhurdairy.5kjnxzp.mongodb.net/?retryWrites=true&w=majority&appName=MadhurDairy";

mongoose
  .connect(dbUrl)
  .then(() => {
    console.log("Connected to MongoDB");
    initDB(); // only run after successful connection
  })
  .catch((err) => {
    console.error("MongoDB Connection Error: ", err);
  });

const initDB = async () => {
  // const products = [
  //   {
  //     name: "Desi Ghee",
  //     category: "Ghee (Clarified Butter)",
  //     description:
  //       "Premium quality ghee (clarified butter) made from fresh milk and processed hygienically. Ideal for daily use.",
  //     image: [
  //       "https://example.com/images/product_1_0.jpg",
  //       "https://example.com/images/product_1_1.jpg",
  //     ],
  //     minQuantity: 5,
  //     quantityUnit: "Pack",
  //     stock: 39,
  //     manufacturingCost: 118.03,
  //     thresholdVal: 6,
  //     price: 98.25,
  //     type: "Low Fat",
  //     totalQuantitySold: 13,
  //     likes: [],
  //     nutrition: {
  //       Protein: "42mg",
  //       Calcium: "85mg",
  //       Fat: "41mg",
  //       Calories: "27mg",
  //     },
  //     shelfLife: 30,
  //     expiryDate: "2025-09-13",
  //     discount: 5,
  //     reviews: [],
  //   },
  //   {
  //     name: "Plain Buttermilk (Chaas)",
  //     category: "Buttermilk (Chaas)",
  //     description:
  //       "Premium quality buttermilk (chaas) made from fresh milk and processed hygienically. Ideal for daily use.",
  //     image: [
  //       "https://example.com/images/product_2_0.jpg",
  //       "https://example.com/images/product_2_1.jpg",
  //       "https://example.com/images/product_2_2.jpg",
  //     ],
  //     minQuantity: 5,
  //     quantityUnit: "Litre",
  //     stock: 1,
  //     manufacturingCost: 110.93,
  //     thresholdVal: 17,
  //     price: 142.24,
  //     type: "Full Cream",
  //     totalQuantitySold: 571,
  //     likes: [],
  //     nutrition: {
  //       Fat: "15mg",
  //       "Vitamin D": "90mg",
  //       Carbohydrates: "71mg",
  //     },
  //     shelfLife: 7,
  //     expiryDate: "2025-07-16",
  //     discount: 20,
  //     reviews: [],
  //   },
  //   {
  //     name: " Masala Buttermilk",
  //     category: "Buttermilk (Chaas)",
  //     description:
  //       "Premium quality buttermilk (chaas) made from fresh milk and processed hygienically. Ideal for daily use.",
  //     image: [
  //       "https://example.com/images/product_3_0.jpg",
  //       "https://example.com/images/product_3_1.jpg",
  //     ],
  //     minQuantity: 5,
  //     quantityUnit: "Litre",
  //     stock: 82,
  //     manufacturingCost: 111.54,
  //     thresholdVal: 11,
  //     price: 92.99,
  //     type: "Organic",
  //     totalQuantitySold: 455,
  //     likes: [],
  //     nutrition: {
  //       Protein: "53mg",
  //       "Vitamin D": "59mg",
  //       Carbohydrates: "29mg",
  //       Fat: "11mg",
  //     },
  //     shelfLife: 30,
  //     expiryDate: "2025-08-25",
  //     discount: 20,
  //     reviews: [],
  //   },
  //   {
  //     name: "Cow Ghee",
  //     category: "Ghee (Clarified Butter)",
  //     description:
  //       "Premium quality ghee (clarified butter) made from fresh milk and processed hygienically. Ideal for daily use.",
  //     image: ["https://example.com/images/product_4_0.jpg"],
  //     minQuantity: 4,
  //     quantityUnit: "Litre",
  //     stock: 20,
  //     manufacturingCost: 75.05,
  //     thresholdVal: 10,
  //     price: 130.41,
  //     type: "Low Fat",
  //     totalQuantitySold: 435,
  //     likes: [],
  //     nutrition: {
  //       Calories: "34mg",
  //       "Vitamin D": "56mg",
  //       Carbohydrates: "95mg",
  //     },
  //     shelfLife: 10,
  //     expiryDate: "2025-09-08",
  //     discount: 10,
  //     reviews: [],
  //   },
  //   {
  //     name: "Chocolate Milk",
  //     category: "Flavored Milk",
  //     description:
  //       "Premium quality flavored milk made from fresh milk and processed hygienically. Ideal for daily use.",
  //     image: [
  //       "https://example.com/images/product_6_0.jpg",
  //       "https://example.com/images/product_6_1.jpg",
  //     ],
  //     minQuantity: 2,
  //     quantityUnit: "Kg",
  //     stock: 75,
  //     manufacturingCost: 59.49,
  //     thresholdVal: 13,
  //     price: 158.63,
  //     type: "Organic",
  //     totalQuantitySold: 191,
  //     likes: [],
  //     nutrition: {
  //       Calcium: "39mg",
  //       Calories: "64mg",
  //       "Vitamin D": "36mg",
  //       Fat: "48mg",
  //     },
  //     shelfLife: 7,
  //     expiryDate: "2025-08-07",
  //     discount: 10,
  //     reviews: [],
  //   },
  //   {
  //     name: " Kesar Shrikhand (Saffron)",
  //     category: "Shrikhand",
  //     description:
  //       "Premium quality shrikhand made from fresh milk and processed hygienically. Ideal for daily use.",
  //     image: [
  //       "https://example.com/images/product_7_0.jpg",
  //       "https://example.com/images/product_7_1.jpg",
  //       "https://example.com/images/product_7_2.jpg",
  //     ],
  //     minQuantity: 1,
  //     quantityUnit: "Pack",
  //     stock: 76,
  //     manufacturingCost: 46.68,
  //     thresholdVal: 18,
  //     price: 89.51,
  //     type: "Regular",
  //     totalQuantitySold: 3,
  //     likes: [],
  //     nutrition: {
  //       "Vitamin D": "39mg",
  //       Protein: "55mg",
  //       Fat: "18mg",
  //     },
  //     shelfLife: 20,
  //     expiryDate: "2025-09-02",
  //     discount: 10,
  //     reviews: [],
  //   },
  //   {
  //     name: "Elaichi Shrikhand (Cardamom)",
  //     category: "Shrikhand",
  //     description:
  //       "Premium quality shrikhand made from fresh milk and processed hygienically. Ideal for daily use.",
  //     image: [
  //       "https://example.com/images/product_8_0.jpg",
  //       "https://example.com/images/product_8_1.jpg",
  //       "https://example.com/images/product_8_2.jpg",
  //     ],
  //     minQuantity: 2,
  //     quantityUnit: "Ml",
  //     stock: 17,
  //     manufacturingCost: 86.25,
  //     thresholdVal: 15,
  //     price: 168.07,
  //     type: "High Protein",
  //     totalQuantitySold: 168,
  //     likes: [],
  //     nutrition: {
  //       Calories: "47mg",
  //       Carbohydrates: "76mg",
  //       Protein: "11mg",
  //     },
  //     shelfLife: 45,
  //     expiryDate: "2025-07-19",
  //     discount: 20,
  //     reviews: [],
  //   },
  //   {
  //     name: " Salted Lassi (Namkeen Lassi)",
  //     category: "Lassi",
  //     description:
  //       "Premium quality lassi made from fresh milk and processed hygienically. Ideal for daily use.",
  //     image: [
  //       "https://example.com/images/product_9_0.jpg",
  //       "https://example.com/images/product_9_1.jpg",
  //       "https://example.com/images/product_9_2.jpg",
  //     ],
  //     minQuantity: 3,
  //     quantityUnit: "Ml",
  //     stock: 21,
  //     manufacturingCost: 56.06,
  //     thresholdVal: 7,
  //     price: 101.19,
  //     type: "Full Cream",
  //     totalQuantitySold: 745,
  //     likes: [],
  //     nutrition: {
  //       Protein: "31mg",
  //       Calcium: "81mg",
  //       Calories: "99mg",
  //     },
  //     shelfLife: 10,
  //     expiryDate: "2025-07-09",
  //     discount: 15,
  //     reviews: [],
  //   },
  //   {
  //     name: "Rasgulla",
  //     category: "Dairy-Based Sweets ",
  //     description:
  //       "Premium quality dairy-based sweets (e.g., rasgulla, gulab jamun, kalakand) made from fresh milk and processed hygienically. Ideal for daily use.",
  //     image: ["https://example.com/images/product_10_0.jpg"],
  //     minQuantity: 5,
  //     quantityUnit: "Gram",
  //     stock: 54,
  //     manufacturingCost: 111.16,
  //     thresholdVal: 16,
  //     price: 120.62,
  //     type: "Regular",
  //     totalQuantitySold: 769,
  //     likes: [],
  //     nutrition: {
  //       "Vitamin D": "29mg",
  //       Protein: "69mg",
  //       Fat: "31mg",
  //     },
  //     shelfLife: 30,
  //     expiryDate: "2025-09-02",
  //     discount: 5,
  //     reviews: [],
  //   },
  //   {
  //     name: "Rasmalai",
  //     category: "Dairy-Based Sweets ",
  //     description:
  //       "Premium quality dairy-based sweets (e.g., rasgulla, gulab jamun, kalakand) made from fresh milk and processed hygienically. Ideal for daily use.",
  //     image: ["https://example.com/images/product_11_0.jpg"],
  //     minQuantity: 4,
  //     quantityUnit: "Kg",
  //     stock: 81,
  //     manufacturingCost: 78.88,
  //     thresholdVal: 12,
  //     price: 58.05,
  //     type: "Low Fat",
  //     totalQuantitySold: 794,
  //     likes: [],
  //     nutrition: {
  //       Carbohydrates: "98mg",
  //       Fat: "17mg",
  //     },
  //     shelfLife: 20,
  //     expiryDate: "2025-08-11",
  //     discount: 15,
  //     reviews: [],
  //   },
  //   {
  //     name: "Buffelo Ghee",
  //     category: "Ghee (Clarified Butter)",
  //     description:
  //       "Premium quality ghee (clarified butter) made from fresh milk and processed hygienically. Ideal for daily use.",
  //     image: [
  //       "https://example.com/images/product_12_0.jpg",
  //       "https://example.com/images/product_12_1.jpg",
  //       "https://example.com/images/product_12_2.jpg",
  //     ],
  //     minQuantity: 1,
  //     quantityUnit: "Pack",
  //     stock: 87,
  //     manufacturingCost: 99.15,
  //     thresholdVal: 11,
  //     price: 131.82,
  //     type: "High Protein",
  //     totalQuantitySold: 590,
  //     likes: [],
  //     nutrition: {
  //       Fat: "11mg",
  //       Protein: "96mg",
  //       "Vitamin D": "84mg",
  //       Calcium: "33mg",
  //     },
  //     shelfLife: 45,
  //     expiryDate: "2025-08-31",
  //     discount: 20,
  //     reviews: [],
  //   },
  //   {
  //     name: "Plane Cream",
  //     category: "Cream",
  //     description:
  //       "Premium quality cream made from fresh milk and processed hygienically. Ideal for daily use.",
  //     image: [
  //       "https://example.com/images/product_13_0.jpg",
  //       "https://example.com/images/product_13_1.jpg",
  //       "https://example.com/images/product_13_2.jpg",
  //     ],
  //     minQuantity: 2,
  //     quantityUnit: "Gram",
  //     stock: 59,
  //     manufacturingCost: 106.3,
  //     thresholdVal: 13,
  //     price: 120.9,
  //     type: "High Protein",
  //     totalQuantitySold: 367,
  //     likes: [],
  //     nutrition: {
  //       Fat: "52mg",
  //       Calcium: "71mg",
  //       Carbohydrates: "1mg",
  //     },
  //     shelfLife: 45,
  //     expiryDate: "2025-08-19",
  //     discount: 10,
  //     reviews: [],
  //   },
  //   {
  //     name: "A2 Ghee",
  //     category: "Ghee (Clarified Butter)",
  //     description:
  //       "Premium quality ghee (clarified butter) made from fresh milk and processed hygienically. Ideal for daily use.",
  //     image: [
  //       "https://example.com/images/product_15_0.jpg",
  //       "https://example.com/images/product_15_1.jpg",
  //     ],
  //     minQuantity: 5,
  //     quantityUnit: "Gram",
  //     stock: 37,
  //     manufacturingCost: 112.27,
  //     thresholdVal: 12,
  //     price: 72.1,
  //     type: "Regular",
  //     totalQuantitySold: 396,
  //     likes: [],
  //     nutrition: {
  //       Calories: "27mg",
  //       Fat: "57mg",
  //       "Vitamin D": "15mg",
  //     },
  //     shelfLife: 15,
  //     expiryDate: "2025-07-28",
  //     discount: 15,
  //     reviews: [],
  //   },
  //   {
  //     name: "Milk Powder Premium 16",
  //     category: "Milk Powder",
  //     description:
  //       "Premium quality milk powder made from fresh milk and processed hygienically. Ideal for daily use.",
  //     image: [
  //       "https://example.com/images/product_16_0.jpg",
  //       "https://example.com/images/product_16_1.jpg",
  //       "https://example.com/images/product_16_2.jpg",
  //     ],
  //     minQuantity: 4,
  //     quantityUnit: "Pack",
  //     stock: 58,
  //     manufacturingCost: 62.0,
  //     thresholdVal: 20,
  //     price: 176.06,
  //     type: "Regular",
  //     totalQuantitySold: 267,
  //     likes: [],
  //     nutrition: {
  //       Protein: "12mg",
  //       "Vitamin D": "77mg",
  //       Calories: "32mg",
  //     },
  //     shelfLife: 15,
  //     expiryDate: "2025-09-27",
  //     discount: 20,
  //     reviews: [],
  //   },
  //   {
  //     name: "Fruit Shrikhand (Mixed Fruit or Mango)",
  //     category: "Shrikhand",
  //     description:
  //       "Premium quality shrikhand made from fresh milk and processed hygienically. Ideal for daily use.",
  //     image: [
  //       "https://example.com/images/product_17_0.jpg",
  //       "https://example.com/images/product_17_1.jpg",
  //       "https://example.com/images/product_17_2.jpg",
  //     ],
  //     minQuantity: 2,
  //     quantityUnit: "Ml",
  //     stock: 37,
  //     manufacturingCost: 58.86,
  //     thresholdVal: 16,
  //     price: 65.5,
  //     type: "Organic",
  //     totalQuantitySold: 876,
  //     likes: [],
  //     nutrition: {
  //       Calcium: "8mg",
  //       Fat: "14mg",
  //       Carbohydrates: "30mg",
  //     },
  //     shelfLife: 15,
  //     expiryDate: "2025-07-16",
  //     discount: 5,
  //     reviews: [],
  //   },
  //   {
  //     name: " Dry Fruit Shrikhand",
  //     category: "Shrikhand",
  //     description:
  //       "Premium quality shrikhand made from fresh milk and processed hygienically. Ideal for daily use.",
  //     image: [
  //       "https://example.com/images/product_18_0.jpg",
  //       "https://example.com/images/product_18_1.jpg",
  //     ],
  //     minQuantity: 1,
  //     quantityUnit: "Pack",
  //     stock: 85,
  //     manufacturingCost: 109.22,
  //     thresholdVal: 13,
  //     price: 129.47,
  //     type: "Full Cream",
  //     totalQuantitySold: 298,
  //     likes: [],
  //     nutrition: {
  //       Calories: "10mg",
  //       Fat: "5mg",
  //       Calcium: "63mg",
  //       Protein: "75mg",
  //     },
  //     shelfLife: 30,
  //     expiryDate: "2025-09-07",
  //     discount: 10,
  //     reviews: [],
  //   },
  //   {
  //     name: "Gulab Jamun",
  //     category: "Dairy-Based Sweets ",
  //     description:
  //       "Premium quality dairy-based sweets (e.g., rasgulla, gulab jamun, kalakand) made from fresh milk and processed hygienically. Ideal for daily use.",
  //     image: [
  //       "https://example.com/images/product_19_0.jpg",
  //       "https://example.com/images/product_19_1.jpg",
  //       "https://example.com/images/product_19_2.jpg",
  //     ],
  //     minQuantity: 5,
  //     quantityUnit: "Litre",
  //     stock: 57,
  //     manufacturingCost: 73.83,
  //     thresholdVal: 15,
  //     price: 180.83,
  //     type: "Regular",
  //     totalQuantitySold: 92,
  //     likes: [],
  //     nutrition: {
  //       Calcium: "88mg",
  //       Calories: "71mg",
  //       Protein: "97mg",
  //     },
  //     shelfLife: 10,
  //     expiryDate: "2025-09-19",
  //     discount: 20,
  //     reviews: [],
  //   },
  //   {
  //     name: "Malai Paneer",
  //     category: "Paneer",
  //     description:
  //       "Premium quality paneer made from fresh milk and processed hygienically. Ideal for daily use.",
  //     image: [
  //       "https://example.com/images/product_20_0.jpg",
  //       "https://example.com/images/product_20_1.jpg",
  //       "https://example.com/images/product_20_2.jpg",
  //     ],
  //     minQuantity: 3,
  //     quantityUnit: "Kg",
  //     stock: 45,
  //     manufacturingCost: 102.17,
  //     thresholdVal: 16,
  //     price: 168.34,
  //     type: "Organic",
  //     totalQuantitySold: 138,
  //     likes: [],
  //     nutrition: {
  //       Calcium: "48mg",
  //       Calories: "6mg",
  //       "Vitamin D": "12mg",
  //       Fat: "22mg",
  //     },
  //     shelfLife: 10,
  //     expiryDate: "2025-07-28",
  //     discount: 15,
  //     reviews: [],
  //   },
  //   {
  //     name: "Mozzarella Cheese",
  //     category: "Cheese",
  //     description:
  //       "Premium quality cheese made from fresh milk and processed hygienically. Ideal for daily use.",
  //     image: [
  //       "https://example.com/images/product_22_0.jpg",
  //       "https://example.com/images/product_22_1.jpg",
  //     ],
  //     minQuantity: 1,
  //     quantityUnit: "Pack",
  //     stock: 62,
  //     manufacturingCost: 91.49,
  //     thresholdVal: 13,
  //     price: 137.08,
  //     type: "Low Fat",
  //     totalQuantitySold: 791,
  //     likes: [],
  //     nutrition: {
  //       Fat: "94mg",
  //       "Vitamin D": "88mg",
  //     },
  //     shelfLife: 15,
  //     expiryDate: "2025-09-06",
  //     discount: 20,
  //     reviews: [],
  //   },
  //   {
  //     name: "Rabri",
  //     category: "Dairy-Based Sweets ",
  //     description:
  //       "Premium quality dairy-based sweets (e.g., rasgulla, gulab jamun, kalakand) made from fresh milk and processed hygienically. Ideal for daily use.",
  //     image: [
  //       "https://example.com/images/product_24_0.jpg",
  //       "https://example.com/images/product_24_1.jpg",
  //       "https://example.com/images/product_24_2.jpg",
  //     ],
  //     minQuantity: 1,
  //     quantityUnit: "Pack",
  //     stock: 86,
  //     manufacturingCost: 82.73,
  //     thresholdVal: 15,
  //     price: 106.13,
  //     type: "Organic",
  //     totalQuantitySold: 288,
  //     likes: [],
  //     nutrition: {
  //       Carbohydrates: "95mg",
  //       Calcium: "95mg",
  //     },
  //     shelfLife: 7,
  //     expiryDate: "2025-08-21",
  //     discount: 20,
  //     reviews: [],
  //   },
  //   {
  //     name: "Milk Cake (Alwar Ka Mawa)",
  //     category: "Dairy-Based Sweets ",
  //     description:
  //       "Premium quality dairy-based sweets (e.g., rasgulla, gulab jamun, kalakand) made from fresh milk and processed hygienically. Ideal for daily use.",
  //     image: ["https://example.com/images/product_26_0.jpg"],
  //     minQuantity: 4,
  //     quantityUnit: "Pack",
  //     stock: 42,
  //     manufacturingCost: 78.69,
  //     thresholdVal: 20,
  //     price: 190.88,
  //     type: "Regular",
  //     totalQuantitySold: 734,
  //     likes: [],
  //     nutrition: {
  //       Carbohydrates: "11mg",
  //       Calcium: "81mg",
  //       "Vitamin D": "43mg",
  //     },
  //     shelfLife: 15,
  //     expiryDate: "2025-09-04",
  //     discount: 5,
  //     reviews: [],
  //   },
  //   {
  //     name: "Plain Yoghurt (Dahi)",
  //     category: "Yogurt",
  //     description:
  //       "Premium quality yogurt made from fresh milk and processed hygienically. Ideal for daily use.",
  //     image: ["https://example.com/images/product_27_0.jpg"],
  //     minQuantity: 5,
  //     quantityUnit: "Gram",
  //     stock: 68,
  //     manufacturingCost: 43.17,
  //     thresholdVal: 7,
  //     price: 128.22,
  //     type: "Full Cream",
  //     totalQuantitySold: 671,
  //     likes: [],
  //     nutrition: {
  //       Calcium: "23mg",
  //       Fat: "95mg",
  //       "Vitamin D": "42mg",
  //     },
  //     shelfLife: 7,
  //     expiryDate: "2025-07-24",
  //     discount: 5,
  //     reviews: [],
  //   },
  //   {
  //     name: " Badam (Almond) Milk",
  //     category: "Flavored Milk",
  //     description:
  //       "Premium quality flavored milk made from fresh milk and processed hygienically. Ideal for daily use.",
  //     image: [
  //       "https://example.com/images/product_28_0.jpg",
  //       "https://example.com/images/product_28_1.jpg",
  //     ],
  //     minQuantity: 5,
  //     quantityUnit: "Kg",
  //     stock: 46,
  //     manufacturingCost: 115.36,
  //     thresholdVal: 8,
  //     price: 86.16,
  //     type: "High Protein",
  //     totalQuantitySold: 288,
  //     likes: [],
  //     nutrition: {
  //       Protein: "2mg",
  //       Fat: "66mg",
  //       Calcium: "32mg",
  //     },
  //     shelfLife: 30,
  //     expiryDate: "2025-09-18",
  //     discount: 20,
  //     reviews: [],
  //   },
  //   {
  //     name: "Kesar (Saffron) Milk",
  //     category: "Flavored Milk",
  //     description:
  //       "Premium quality flavored milk made from fresh milk and processed hygienically. Ideal for daily use.",
  //     image: [
  //       "https://example.com/images/product_29_0.jpg",
  //       "https://example.com/images/product_29_1.jpg",
  //       "https://example.com/images/product_29_2.jpg",
  //     ],
  //     minQuantity: 2,
  //     quantityUnit: "Litre",
  //     stock: 45,
  //     manufacturingCost: 75.19,
  //     thresholdVal: 13,
  //     price: 158.13,
  //     type: "High Protein",
  //     totalQuantitySold: 548,
  //     likes: [],
  //     nutrition: {
  //       Calcium: "34mg",
  //       Fat: "85mg",
  //       Protein: "35mg",
  //       "Vitamin D": "27mg",
  //     },
  //     shelfLife: 30,
  //     expiryDate: "2025-08-25",
  //     discount: 15,
  //     reviews: [],
  //   },
  //   {
  //     name: "Unsalted Butter",
  //     category: "Butter",
  //     description:
  //       "Premium quality butter made from fresh milk and processed hygienically. Ideal for daily use.",
  //     image: ["https://example.com/images/product_31_0.jpg"],
  //     minQuantity: 5,
  //     quantityUnit: "Gram",
  //     stock: 100,
  //     manufacturingCost: 71.21,
  //     thresholdVal: 5,
  //     price: 155.33,
  //     type: "Organic",
  //     totalQuantitySold: 965,
  //     likes: [],
  //     nutrition: {
  //       Protein: "59mg",
  //       "Vitamin D": "80mg",
  //       Calories: "7mg",
  //     },
  //     shelfLife: 30,
  //     expiryDate: "2025-09-02",
  //     discount: 20,
  //     reviews: [],
  //   },
  //   {
  //     name: " Cardamom (Elaichi) Milk",
  //     category: "Flavored Milk",
  //     description:
  //       "Premium quality flavored milk made from fresh milk and processed hygienically. Ideal for daily use.",
  //     image: [
  //       "https://example.com/images/product_32_0.jpg",
  //       "https://example.com/images/product_32_1.jpg",
  //     ],
  //     minQuantity: 4,
  //     quantityUnit: "Kg",
  //     stock: 88,
  //     manufacturingCost: 64.67,
  //     thresholdVal: 5,
  //     price: 59.79,
  //     type: "Full Cream",
  //     totalQuantitySold: 947,
  //     likes: [],
  //     nutrition: {
  //       "Vitamin D": "71mg",
  //       Carbohydrates: "30mg",
  //       Calcium: "58mg",
  //       Calories: "92mg",
  //     },
  //     shelfLife: 45,
  //     expiryDate: "2025-09-19",
  //     discount: 20,
  //     reviews: [],
  //   },
  //   {
  //     name: "Flavoured Yoghurt",
  //     category: "Yogurt",
  //     description:
  //       "Premium quality yogurt made from fresh milk and processed hygienically. Ideal for daily use.",
  //     image: [
  //       "https://example.com/images/product_34_0.jpg",
  //       "https://example.com/images/product_34_1.jpg",
  //     ],
  //     minQuantity: 2,
  //     quantityUnit: "Kg",
  //     stock: 59,
  //     manufacturingCost: 72.16,
  //     thresholdVal: 15,
  //     price: 69.31,
  //     type: "Full Cream",
  //     totalQuantitySold: 989,
  //     likes: [],
  //     nutrition: {
  //       "Vitamin D": "77mg",
  //       Fat: "26mg",
  //       Carbohydrates: "46mg",
  //     },
  //     shelfLife: 15,
  //     expiryDate: "2025-08-23",
  //     discount: 15,
  //     reviews: [],
  //   },
  //   {
  //     name: "Sweet Malai Lassi",
  //     category: "Lassi",
  //     description:
  //       "Premium quality lassi made from fresh milk and processed hygienically. Ideal for daily use.",
  //     image: [
  //       "https://example.com/images/product_35_0.jpg",
  //       "https://example.com/images/product_35_1.jpg",
  //     ],
  //     minQuantity: 1,
  //     quantityUnit: "Kg",
  //     stock: 40,
  //     manufacturingCost: 71.08,
  //     thresholdVal: 13,
  //     price: 136.45,
  //     type: "Regular",
  //     totalQuantitySold: 8,
  //     likes: [],
  //     nutrition: {
  //       Calories: "100mg",
  //       Protein: "92mg",
  //       Calcium: "29mg",
  //       Fat: "66mg",
  //     },
  //     shelfLife: 45,
  //     expiryDate: "2025-09-04",
  //     discount: 20,
  //     reviews: [],
  //   },
  //   {
  //     name: "Kalakand",
  //     category: "Dairy-Based Sweets ",
  //     description:
  //       "Premium quality dairy-based sweets (e.g., rasgulla, gulab jamun, kalakand) made from fresh milk and processed hygienically. Ideal for daily use.",
  //     image: [
  //       "https://example.com/images/product_37_0.jpg",
  //       "https://example.com/images/product_37_1.jpg",
  //     ],
  //     minQuantity: 5,
  //     quantityUnit: "Gram",
  //     stock: 77,
  //     manufacturingCost: 45.95,
  //     thresholdVal: 17,
  //     price: 58.95,
  //     type: "Regular",
  //     totalQuantitySold: 832,
  //     likes: [],
  //     nutrition: {
  //       Calories: "22mg",
  //       Calcium: "31mg",
  //       Carbohydrates: "47mg",
  //       "Vitamin D": "63mg",
  //     },
  //     shelfLife: 20,
  //     expiryDate: "2025-07-09",
  //     discount: 20,
  //     reviews: [],
  //   },
  //   {
  //     name: "Mango Lassi",
  //     category: "Lassi",
  //     description:
  //       "Premium quality lassi made from fresh milk and processed hygienically. Ideal for daily use.",
  //     image: [
  //       "https://example.com/images/product_38_0.jpg",
  //       "https://example.com/images/product_38_1.jpg",
  //       "https://example.com/images/product_38_2.jpg",
  //     ],
  //     minQuantity: 4,
  //     quantityUnit: "Kg",
  //     stock: 4,
  //     manufacturingCost: 60.56,
  //     thresholdVal: 13,
  //     price: 165.14,
  //     type: "Low Fat",
  //     totalQuantitySold: 571,
  //     likes: [],
  //     nutrition: {
  //       Fat: "84mg",
  //       Calories: "63mg",
  //       Carbohydrates: "18mg",
  //       Calcium: "86mg",
  //     },
  //     shelfLife: 7,
  //     expiryDate: "2025-07-23",
  //     discount: 5,
  //     reviews: [],
  //   },
  //   {
  //     name: "Mint / Masala Lassi",
  //     category: "Lassi",
  //     description:
  //       "Premium quality lassi made from fresh milk and processed hygienically. Ideal for daily use.",
  //     image: [
  //       "https://example.com/images/product_39_0.jpg",
  //       "https://example.com/images/product_39_1.jpg",
  //       "https://example.com/images/product_39_2.jpg",
  //     ],
  //     minQuantity: 2,
  //     quantityUnit: "Litre",
  //     stock: 44,
  //     manufacturingCost: 83.76,
  //     thresholdVal: 13,
  //     price: 169.34,
  //     type: "Regular",
  //     totalQuantitySold: 333,
  //     likes: [],
  //     nutrition: {
  //       Calcium: "22mg",
  //       Fat: "80mg",
  //       Carbohydrates: "70mg",
  //     },
  //     shelfLife: 20,
  //     expiryDate: "2025-08-01",
  //     discount: 5,
  //     reviews: [],
  //   },
  //   {
  //     name: "Basundi",
  //     category: "Dairy-Based Sweets ",
  //     description:
  //       "Premium quality dairy-based sweets (e.g., rasgulla, gulab jamun, kalakand) made from fresh milk and processed hygienically. Ideal for daily use.",
  //     image: [
  //       "https://example.com/images/product_40_0.jpg",
  //       "https://example.com/images/product_40_1.jpg",
  //       "https://example.com/images/product_40_2.jpg",
  //     ],
  //     minQuantity: 4,
  //     quantityUnit: "Pack",
  //     stock: 43,
  //     manufacturingCost: 112.22,
  //     thresholdVal: 15,
  //     price: 194.15,
  //     type: "Organic",
  //     totalQuantitySold: 896,
  //     likes: [],
  //     nutrition: {
  //       "Vitamin D": "84mg",
  //       Fat: "44mg",
  //       Calories: "62mg",
  //     },
  //     shelfLife: 15,
  //     expiryDate: "2025-08-15",
  //     discount: 15,
  //     reviews: [],
  //   },
  //   {
  //     name: "Mint Buttermilk (Pudina Chaas)",
  //     category: "Buttermilk (Chaas)",
  //     description:
  //       "Premium quality buttermilk (chaas) made from fresh milk and processed hygienically. Ideal for daily use.",
  //     image: [
  //       "https://example.com/images/product_42_0.jpg",
  //       "https://example.com/images/product_42_1.jpg",
  //       "https://example.com/images/product_42_2.jpg",
  //     ],
  //     minQuantity: 4,
  //     quantityUnit: "Pack",
  //     stock: 24,
  //     manufacturingCost: 66.81,
  //     thresholdVal: 20,
  //     price: 111.24,
  //     type: "Low Fat",
  //     totalQuantitySold: 132,
  //     likes: [],
  //     nutrition: {
  //       Protein: "8mg",
  //       "Vitamin D": "90mg",
  //     },
  //     shelfLife: 45,
  //     expiryDate: "2025-09-21",
  //     discount: 10,
  //     reviews: [],
  //   },
  //   {
  //     name: "Sandesh",
  //     category: "Dairy-Based Sweets ",
  //     description:
  //       "Premium quality dairy-based sweets (e.g., rasgulla, gulab jamun, kalakand) made from fresh milk and processed hygienically. Ideal for daily use.",
  //     image: [
  //       "https://example.com/images/product_45_0.jpg",
  //       "https://example.com/images/product_45_1.jpg",
  //     ],
  //     minQuantity: 4,
  //     quantityUnit: "Gram",
  //     stock: 77,
  //     manufacturingCost: 80.39,
  //     thresholdVal: 8,
  //     price: 173.34,
  //     type: "Organic",
  //     totalQuantitySold: 327,
  //     likes: [],
  //     nutrition: {
  //       Protein: "21mg",
  //       "Vitamin D": "69mg",
  //     },
  //     shelfLife: 30,
  //     expiryDate: "2025-07-13",
  //     discount: 5,
  //     reviews: [],
  //   },
  //   {
  //     name: "Processed Cheese",
  //     category: "Cheese",
  //     description:
  //       "Premium quality cheese made from fresh milk and processed hygienically. Ideal for daily use.",
  //     image: ["https://example.com/images/product_47_0.jpg"],
  //     minQuantity: 5,
  //     quantityUnit: "Litre",
  //     stock: 15,
  //     manufacturingCost: 45.18,
  //     thresholdVal: 5,
  //     price: 123.25,
  //     type: "Full Cream",
  //     totalQuantitySold: 411,
  //     likes: [],
  //     nutrition: {
  //       Carbohydrates: "92mg",
  //       Calcium: "27mg",
  //       Calories: "83mg",
  //     },
  //     shelfLife: 15,
  //     expiryDate: "2025-09-20",
  //     discount: 5,
  //     reviews: [],
  //   },
  //   {
  //     name: "Hybrid Paneer",
  //     category: "Paneer",
  //     description:
  //       "Premium quality paneer made from fresh milk and processed hygienically. Ideal for daily use.",
  //     image: [
  //       "https://example.com/images/product_48_0.jpg",
  //       "https://example.com/images/product_48_1.jpg",
  //     ],
  //     minQuantity: 1,
  //     quantityUnit: "Litre",
  //     stock: 4,
  //     manufacturingCost: 83.19,
  //     thresholdVal: 19,
  //     price: 118.31,
  //     type: "Low Fat",
  //     totalQuantitySold: 734,
  //     likes: [],
  //     nutrition: {
  //       Calcium: "64mg",
  //       "Vitamin D": "16mg",
  //       Fat: "84mg",
  //     },
  //     shelfLife: 15,
  //     expiryDate: "2025-09-08",
  //     discount: 20,
  //     reviews: [],
  //   },
  //   {
  //     name: "South Indian Spiced Buttermilk (Neer Mor)",
  //     category: "Buttermilk (Chaas)",
  //     description:
  //       "Premium quality buttermilk (chaas) made from fresh milk and processed hygienically. Ideal for daily use.",
  //     image: ["https://example.com/images/product_49_0.jpg"],
  //     minQuantity: 4,
  //     quantityUnit: "Ml",
  //     stock: 40,
  //     manufacturingCost: 81.73,
  //     thresholdVal: 7,
  //     price: 128.42,
  //     type: "Full Cream",
  //     totalQuantitySold: 886,
  //     likes: [],
  //     nutrition: {
  //       "Vitamin D": "49mg",
  //       Calories: "67mg",
  //       Fat: "9mg",
  //     },
  //     shelfLife: 10,
  //     expiryDate: "2025-07-08",
  //     discount: 10,
  //     reviews: [],
  //   },
  //   {
  //     name: "Sweet Buttermilk",
  //     category: "Buttermilk (Chaas)",
  //     description:
  //       "Premium quality buttermilk (chaas) made from fresh milk and processed hygienically. Ideal for daily use.",
  //     image: ["https://example.com/images/product_50_0.jpg"],
  //     minQuantity: 3,
  //     quantityUnit: "Ml",
  //     stock: 11,
  //     manufacturingCost: 52.57,
  //     thresholdVal: 8,
  //     price: 127.29,
  //     type: "Organic",
  //     totalQuantitySold: 261,
  //     likes: [],
  //     nutrition: {
  //       Calories: "95mg",
  //       Carbohydrates: "45mg",
  //       Fat: "3mg",
  //     },
  //     shelfLife: 7,
  //     expiryDate: "2025-07-21",
  //     discount: 20,
  //     reviews: [],
  //   },
  // ];

  // try {

  //   await Product.insertMany(products);

  //   console.log("Insertion successful")

  // } catch (error) {
  //   console.error("Error during DB initialization:", error);
  // } finally {
  //   mongoose.disconnect();
  // }
};
